import type { ModelProfile } from '@/lib/models/model-router'

export const DEFAULT_PROFILES: ModelProfile[] = [
  {
    id: 'ollama-llama3-fast',
    provider: 'ollama',
    modelName: 'llama3.2:3b',
    executionMode: 'local',
    strengths: ['fast', 'low-cost', 'private'],
    weaknesses: ['limited-reasoning', 'short-context'],
    recommendedWorkloads: ['summarization', 'classification', 'context-compression'],
    privacyModes: ['local-only', 'hybrid', 'cloud-approved'],
    costClass: 'free-local',
    healthStatus: 'unknown',
    maxContextTokens: 8192,
    localEndpoint: 'http://localhost:11434',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ollama-bge-m3',
    provider: 'ollama',
    modelName: 'bge-m3',
    executionMode: 'local',
    strengths: ['embeddings', 'semantic-search', 'private'],
    weaknesses: ['text-generation-only-embedding'],
    recommendedWorkloads: ['embedding'],
    privacyModes: ['local-only', 'hybrid', 'cloud-approved'],
    costClass: 'free-local',
    healthStatus: 'unknown',
    maxContextTokens: 8192,
    localEndpoint: 'http://localhost:11434',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'anthropic-haiku',
    provider: 'anthropic',
    modelName: 'claude-haiku-4-5',
    executionMode: 'cloud',
    strengths: ['fast', 'affordable', 'reliable'],
    weaknesses: ['cloud-only', 'metered-cost'],
    recommendedWorkloads: ['classification', 'summarization', 'planning'],
    privacyModes: ['hybrid', 'cloud-approved'],
    costClass: 'metered-low',
    healthStatus: 'unknown',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'anthropic-sonnet',
    provider: 'anthropic',
    modelName: 'claude-sonnet-4-6',
    executionMode: 'cloud',
    strengths: ['strong-reasoning', 'coding', 'large-context'],
    weaknesses: ['cloud-only', 'higher-cost'],
    recommendedWorkloads: ['coding', 'review', 'risk-analysis', 'planning'],
    privacyModes: ['hybrid', 'cloud-approved'],
    costClass: 'metered-high',
    healthStatus: 'unknown',
    maxContextTokens: 200000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'claude-code-agent',
    provider: 'claude-code',
    modelName: 'claude-code',
    executionMode: 'desktop-agent',
    strengths: ['coding', 'refactoring', 'tests', 'file-editing'],
    weaknesses: ['subscription-based', 'interactive'],
    recommendedWorkloads: ['coding', 'review'],
    privacyModes: ['hybrid', 'cloud-approved'],
    costClass: 'included-subscription',
    healthStatus: 'healthy',
    updatedAt: new Date().toISOString(),
  },
]
