import type { AgentProfile } from '@/lib/models/agent-profile'

const now = new Date().toISOString()

export const DEFAULT_AGENT_PROFILES: AgentProfile[] = [
  {
    id: 'product-planner',
    displayName: 'Product Planner',
    role: 'product-planner',
    availability: 'available',
    autonomyLevel: 'propose-only',
    strengths: ['scope-definition', 'requirements', 'roadmap', 'risk-identification'],
    limits: ['no-direct-code-changes', 'needs-human-approval-for-scope-changes'],
    preferredWorkloads: ['planning', 'risk-analysis'],
    allowedToolIds: ['Read', 'WebSearch', 'WebFetch'],
    skillRefs: [
      { id: 'skill-context-fetch', title: 'Context Fetch', path: 'Agent_Skills/skill-context-fetch.md' },
      { id: 'skill-escalate', title: 'Escalate', path: 'Agent_Skills/skill-escalate.md' },
    ],
    costClass: 'metered-high',
    defaultModelProfileId: 'anthropic-sonnet',
    updatedAt: now,
  },
  {
    id: 'architect',
    displayName: 'Architect',
    role: 'architect',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['domain-models', 'api-design', 'adr-writing', 'interface-design'],
    limits: ['no-ui-code', 'no-production-deploys'],
    preferredWorkloads: ['planning', 'coding', 'review'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'WebSearch'],
    skillRefs: [
      { id: 'skill-context-fetch', title: 'Context Fetch', path: 'Agent_Skills/skill-context-fetch.md' },
      { id: 'skill-writeback', title: 'Write Back', path: 'Agent_Skills/skill-writeback.md' },
    ],
    costClass: 'metered-high',
    defaultModelProfileId: 'anthropic-sonnet',
    updatedAt: now,
  },
  {
    id: 'backend-engineer',
    displayName: 'Backend Engineer',
    role: 'backend-engineer',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['api-routes', 'persistence', 'tests', 'refactoring'],
    limits: ['no-ui-components', 'no-production-secrets'],
    preferredWorkloads: ['coding', 'review'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-writeback', title: 'Write Back', path: 'Agent_Skills/skill-writeback.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'frontend-saas-designer',
    displayName: 'Frontend / SaaS Designer',
    role: 'frontend-saas-designer',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['react-components', 'ui-ux', 'saas-dashboards', 'tailwind'],
    limits: ['no-backend-logic', 'no-database-changes'],
    preferredWorkloads: ['ui-design', 'coding'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'local-ai-worker',
    displayName: 'Local AI Worker',
    role: 'local-ai-worker',
    availability: 'available',
    autonomyLevel: 'autopilot',
    strengths: ['embeddings', 'classification', 'summarization', 'context-compression'],
    limits: ['no-code-changes', 'local-only-data-access'],
    preferredWorkloads: ['embedding', 'classification', 'summarization', 'context-compression'],
    allowedToolIds: [],
    skillRefs: [],
    costClass: 'free-local',
    defaultModelProfileId: 'ollama-llama3-fast',
    updatedAt: now,
  },
  {
    id: 'qa-reviewer',
    displayName: 'QA Reviewer',
    role: 'qa-reviewer',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['test-writing', 'regression-detection', 'acceptance-criteria'],
    limits: ['no-feature-implementation', 'no-production-deploys'],
    preferredWorkloads: ['review', 'coding'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'Grep'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'security-reviewer',
    displayName: 'Security Reviewer',
    role: 'critic-reviewer',
    availability: 'available',
    autonomyLevel: 'propose-only',
    strengths: ['auth-review', 'secrets-review', 'ssrf-checks', 'logging-safety', 'risk-analysis'],
    limits: ['no-direct-code-changes', 'no-secret-access', 'requires-human-approval-for-security-exceptions'],
    preferredWorkloads: ['review', 'risk-analysis', 'planning'],
    allowedToolIds: ['Read', 'Grep', 'WebSearch'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-escalate', title: 'Escalate', path: 'Agent_Skills/skill-escalate.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'database-engineer',
    displayName: 'Database Engineer',
    role: 'backend-engineer',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['postgres', 'migrations', 'data-consistency', 'backfill', 'transaction-safety'],
    limits: ['no-production-data-access', 'requires-backup-plan-for-destructive-migrations'],
    preferredWorkloads: ['coding', 'review', 'data-model'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-writeback', title: 'Write Back', path: 'Agent_Skills/skill-writeback.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'release-manager',
    displayName: 'Release Manager',
    role: 'devops-automation',
    availability: 'available',
    autonomyLevel: 'propose-only',
    strengths: ['pr-readiness', 'ci-cd', 'rollback-planning', 'release-notes', 'deployment-checks'],
    limits: ['no-direct-production-deploys', 'no-force-push', 'requires-human-approval-before-merge'],
    preferredWorkloads: ['review', 'planning', 'infrastructure'],
    allowedToolIds: ['Read', 'Bash', 'Grep'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-escalate', title: 'Escalate', path: 'Agent_Skills/skill-escalate.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'devops-automation',
    displayName: 'DevOps / Automation',
    role: 'devops-automation',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['n8n-workflows', 'docker', 'ci-cd', 'health-checks'],
    limits: ['no-production-secrets', 'no-force-push'],
    preferredWorkloads: ['coding', 'review'],
    allowedToolIds: ['Bash', 'Read', 'Write', 'Edit'],
    skillRefs: [],
    costClass: 'included-subscription',
    defaultModelProfileId: 'claude-code-agent',
    updatedAt: now,
  },
  {
    id: 'knowledge-curator',
    displayName: 'Knowledge Curator',
    role: 'knowledge-curator',
    availability: 'available',
    autonomyLevel: 'supervised-write',
    strengths: ['nas-documentation', 'adr-writing', 'knowledge-writeback', 'index-maintenance'],
    limits: ['no-production-code-changes', 'no-secrets-access'],
    preferredWorkloads: ['summarization', 'planning'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'WebSearch'],
    skillRefs: [
      { id: 'skill-writeback', title: 'Write Back', path: 'Agent_Skills/skill-writeback.md' },
      { id: 'skill-context-fetch', title: 'Context Fetch', path: 'Agent_Skills/skill-context-fetch.md' },
    ],
    costClass: 'metered-low',
    defaultModelProfileId: 'anthropic-haiku',
    updatedAt: now,
  },
  {
    id: 'hermes-local-critic',
    displayName: 'Hermes Local Critic',
    role: 'critic-reviewer',
    availability: 'available',
    autonomyLevel: 'propose-only',
    strengths: ['local-critique', 'planning-review', 'risk-analysis', 'second-opinion'],
    limits: ['no-direct-code-changes', 'requires-local-model-availability', 'no-secret-access'],
    preferredWorkloads: ['review', 'risk-analysis', 'planning', 'summarization'],
    allowedToolIds: ['Read', 'Grep'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-escalate', title: 'Escalate', path: 'Agent_Skills/skill-escalate.md' },
    ],
    costClass: 'free-local',
    defaultModelProfileId: 'ollama-hermes-local',
    updatedAt: now,
  },
  {
    id: 'openclaw-coding-agent',
    displayName: 'OpenClaw Coding Agent',
    role: 'external-coding-agent',
    availability: 'disabled',
    autonomyLevel: 'supervised-write',
    strengths: ['external-code-generation', 'repo-navigation', 'implementation-drafts'],
    limits: ['disabled-until-cli-or-endpoint-configured', 'no-production-secrets', 'requires-human-review-before-merge'],
    preferredWorkloads: ['coding', 'review', 'refactor'],
    allowedToolIds: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    skillRefs: [
      { id: 'skill-verify', title: 'Verify', path: 'Agent_Skills/skill-verify.md' },
      { id: 'skill-writeback', title: 'Write Back', path: 'Agent_Skills/skill-writeback.md' },
    ],
    costClass: 'included-subscription',
    defaultModelProfileId: 'openclaw-agent',
    updatedAt: now,
  },
]
